# This file generates the GitHub Actions matrix.

# board:
#   - nice_nano_v2

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle dongle_screen
  - settings_reset

format:
  - bt
  - dongle
  - reset

keymap:
  - qwerty

include:
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    keymap: qwerty
    format: dongle
    shield: charybdis_dongle dongle_screen
    artifact-name: charybdis_qwerty_dongle_yads
